version: "3.9"

services:
  gunicorn: 
    restart: always
    container_name: prod_gunicorn
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "8001"
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
      - ./database/db.sqlite3:/code/database/db.sqlite3
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn transf.wsgi:application -b 0.0.0.0:8001 --workers 3"
  nginx:
    restart: always
    container_name: prod_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/code/staticfiles
    depends_on:
      - gunicorn